### ISSUE TITLE
Dutch translation not fully working

### ISSUE THREAD

**Issue by Koning-Chocolademelk** [CachyOS/CachyOS-Welcome#82]
Hi, for the Dutch translation it seems like it:
A: Does not translate everything even if its translated in  /18n/nl/cachyos_hello.ft . For example the thank you message.
B: Does not show up in the language selecting drop down menu (see image)
![afbeelding](https://github.com/user-attachments/assets/3f453949-d731-49b3-8f0c-11c8322e03b6)
Thanks beforehand, greetings 
      Koning-Chocolademelk

**Comment by vnepogodin** [comment]
> Hi, for the Dutch translation it seems like it: A: Does not translate everything even if its translated in /18n/nl/cachyos_hello.ft . For example the thank you message. B: Does not show up in the language selecting drop down menu (see image) ![afbeelding](https://private-user-images.githubusercontent.com/93427299/368172704-3f453949-d731-49b3-8f0c-11c8322e03b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Nzg3MzksIm5iZiI6MTcyNjU3ODQzOSwicGF0aCI6Ii85MzQyNzI5OS8zNjgxNzI3MDQtM2Y0NTM5NDktZDczMS00OWIzLThmMGMtMTFjODMyMmUwM2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEzMDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNDFiOGNiODRlYzZiNDVlYTBkMWVhMWMxMzBjYjA0M2QyZmMyNzA5MThhM2Y4NmE3ZTkxYjk4MDBkOTk3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LaZNq_-vGGlLu9Lgnv_eHC8HEU-cbn_w29BH3-3bhyU) Thanks beforehand, greetings Koning-Chocolademelk

Hi, @Koning-Chocolademelk 

the Dutch language must be put manually into the language dropdown to show up there. see the UI [file](https://github.com/CachyOS/CachyOS-Welcome/blob/develop/ui/cachyos-hello.glade#L286)

regarding text pages, they are translated in each folder which contains translated pages https://github.com/CachyOS/CachyOS-Welcome/tree/develop/data/pages

**Comment by Koning-Chocolademelk** [comment]
> the Dutch language must be put manually into the language dropdown to show up there. see the UI [file](https://github.com/CachyOS/CachyOS-Welcome/blob/develop/ui/cachyos-hello.glade#L286)

I will try this later, is there an reason why that is not done on default?

> regarding text pages, they are translated in each folder which contains translated pages https://github.com/CachyOS/CachyOS-Welcome/tree/develop/data/pages

I am not talking about that, I am talking about things that are translated in the translation file but not on the screen. Maybe adding it to the menu fixes it but again i will try that later when I am able to do that. I am talking about the following example:
![afbeelding](https://github.com/user-attachments/assets/3f4a3a96-78d4-4400-be51-c748cdda24cd)
It doesnt show up, but the string is translated:
![afbeelding](https://github.com/user-attachments/assets/8f054f0c-df1d-4cb0-b8fd-a582dfcf08a3)

**Comment by vnepogodin** [comment]
> It doesnt show up, but the string is translated

![image](https://github.com/user-attachments/assets/4efc6ae4-77f3-41c1-b016-7ae97a6c962c)

works fine if you put Dutch into UI file

**Comment by Koning-Chocolademelk** [comment]
Tried it outaswell, was there any reason to not put it in by defauly?

**Comment by vnepogodin** [comment]
> Tried it outaswell, was there any reason to not put it in by defauly?

wasn't just implemented
